name = "CE: Movement"
prefix = "cem"
author = "Cluster Mod Team"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_cem_ca.paa",
    "meta.cpp",
]
exclude = [
    "addons/*/README.md"
]

[version]
git_hash = 0

[asc]
enabled = true
exclude = [
  "dev"
]

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "2369477168", # Advanced Developer Tools Workshop ID
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]
executable = "arma3"