class CfgMovesBasic {
    class Default;
    class NoActions;
    class Actions {
        class CivilStandActions;
        class CivilProneActions: CivilStandActions {
            SecondaryWeapon = "CCM_LauncherProne";
            weaponOn = "CCM_LauncherProne";
        };
        class PistolStandActions;
        class PistolProneActions: PistolStandActions {
            SecondaryWeapon = "CCM_LauncherProne";
            weaponOn = "CCM_LauncherProne";
        };
        class RifleBaseStandActions;
        class RifleProneActions: RifleBaseStandActions {
            SecondaryWeapon = "CCM_LauncherProne";
            weaponOn = "CCM_LauncherProne";
            weaponOff = "AmovPpneMstpSrasWrflDnon";
        };
        class LauncherKneelActions: NoActions {
            Lying = "AmovPknlMstpSrasWlnrDnon";
            PlayerProne = "AmovPknlMstpSrasWlnrDnon";
            Down = "AmovPknlMstpSrasWlnrDnon";
        };
        class LauncherStandActions: LauncherKneelActions {
            Default = "AmovPercMstpSrasWlnrDnon";
            PlayerStand = "AmovPercMstpSrasWlnrDnon";
            Stand = "AmovPercMstpSrasWlnrDnon";
            Up = "AmovPknlMstpSrasWlnrDnon";
            Lying = "AmovPercMstpSrasWlnrDnon";
            PlayerProne = "AmovPercMstpSrasWlnrDnon";
            Down = "AmovPercMstpSrasWlnrDnon";
        };
        class CCM_LauncherProneActions: LauncherKneelActions {
            StopRelaxed = "CCM_LauncherProne";
            Default = "CCM_LauncherProne";
            Up = "CCM_LauncherProne";
            Crouch = "CCM_LauncherProne";
            PlayerCrouch = "CCM_LauncherProne";
            Down = "CCM_LauncherProne";
            Stand = "CCM_LauncherProne";
            PlayerStand = "CCM_LauncherProne";
            TurnL = "AmovPpneMrunSrasWlnr_turnL";
            TurnLRelaxed = "AmovPpneMrunSrasWlnr_turnL";
            TurnR = "AmovPpneMrunSrasWlnr_turnR";
            TurnRRelaxed = "AmovPpneMrunSrasWlnr_turnR";
            Stop = "CCM_LauncherProne";
            Civil = "AmovPpneMstpSnonWnonDnon";
            CivilLying = "AmovPpneMstpSnonWnonDnon";
            BinocOff = "CCM_LauncherProne";
            Gear = "AinvPpneMstpSnonWnonDnon";
            BinocOn = "AwopPpneMstpSoptWbinDnon_Lnr";
            HandGunOn = "AmovPpneMstpSrasWpstDnon";
            stance = "ManStanceProne";
            ReloadRPG = "LauncherProne_Reload_Start";
            //GestureReloadRPG7[] = {"GestureReloadRPG7Kneel", "Gesture"};
            weaponOn = "CCM_LauncherProne";
            WeaponOff = "AmovPpneMstpSrasWrflDnon";
            WalkB = "AmovPpneMrunSrasWlnrDb";
            WalkRB = "AmovPpneMrunSrasWlnrDbr";
            WalkLB = "AmovPpneMrunSrasWlnrDbl";
            WalkR = "AmovPpneMrunSrasWlnrDr";
            WalkL = "AmovPpneMrunSrasWlnrDl";
            WalkRF = "AmovPpneMrunSrasWlnrDfr";
            WalkLF = "AmovPpneMrunSrasWlnrDfl";
            WalkF = "AmovPpneMrunSrasWlnrDf";
            PlayerWalkB = "AmovPpneMrunSrasWlnrDb";
            PlayerWalkRB = "AmovPpneMrunSrasWlnrDbr";
            PlayerWalkLB = "AmovPpneMrunSrasWlnrDbl";
            PlayerWalkR = "AmovPpneMrunSrasWlnrDr";
            PlayerWalkL = "AmovPpneMrunSrasWlnrDl";
            PlayerWalkRF = "AmovPpneMrunSrasWlnrDfr";
            PlayerWalkLF = "AmovPpneMrunSrasWlnrDfl";
            PlayerWalkF = "AmovPpneMrunSrasWlnrDf";
            SlowF = "AmovPpneMrunSrasWlnrDf";
            SlowLF = "AmovPpneMrunSrasWlnrDfl";
            SlowRF = "AmovPpneMrunSrasWlnrDfr";
            SlowL = "AmovPpneMrunSrasWlnrDl";
            SlowR = "AmovPpneMrunSrasWlnrDr";
            SlowLB = "AmovPpneMrunSrasWlnrDbl";
            SlowRB = "AmovPpneMrunSrasWlnrDbr";
            SlowB = "AmovPpneMrunSrasWlnrDb";
            PlayerSlowF = "AmovPpneMrunSrasWlnrDf";
            PlayerSlowLF = "AmovPpneMrunSrasWlnrDfl";
            PlayerSlowRF = "AmovPpneMrunSrasWlnrDfr";
            PlayerSlowL = "AmovPpneMrunSrasWlnrDl";
            PlayerSlowR = "AmovPpneMrunSrasWlnrDr";
            PlayerSlowLB = "AmovPpneMrunSrasWlnrDbl";
            PlayerSlowRB = "AmovPpneMrunSrasWlnrDbr";
            PlayerSlowB = "AmovPpneMrunSrasWlnrDb";
            FastF = "AmovPpneMrunSrasWlnrDf";
            FastLF = "AmovPpneMrunSrasWlnrDfl";
            FastRF = "AmovPpneMrunSrasWlnrDfr";
            FastL = "AmovPpneMrunSrasWlnrDl";
            FastR = "AmovPpneMrunSrasWlnrDr";
            FastLB = "AmovPpneMrunSrasWlnrDbl";
            FastRB = "AmovPpneMrunSrasWlnrDr";
            FastB = "AmovPpneMrunSrasWlnrDb";
            TactB = "AmovPpneMrunSrasWlnrDb";
            TactRB = "AmovPpneMrunSrasWlnrDbr";
            TactLB = "AmovPpneMrunSrasWlnrDbl";
            TactR = "AmovPpneMrunSrasWlnrDr";
            TactL = "AmovPpneMrunSrasWlnrDl";
            TactRF = "AmovPpneMrunSrasWlnrDfr";
            TactLF = "AmovPpneMrunSrasWlnrDfl";
            TactF = "AmovPpneMrunSrasWlnrDf";
            PlayerTactB = "AmovPpneMrunSrasWlnrDb";
            PlayerTactRB = "AmovPpneMrunSrasWlnrDbr";
            PlayerTactLB = "AmovPpneMrunSrasWlnrDbl";
            PlayerTactR = "AmovPpneMrunSrasWlnrDr";
            PlayerTactL = "AmovPpneMrunSrasWlnrDl";
            PlayerTactRF = "AmovPpneMrunSrasWlnrDfr";
            PlayerTactLF = "AmovPpneMrunSrasWlnrDfl";
            PlayerTactF = "AmovPpneMrunSrasWlnrDf";
        };
        class BinocProneLnrActions: LauncherKneelActions {
            BinocOff = "CCM_LauncherProne";
            SecondaryWeapon = "CCM_LauncherProne";
            weaponOn = "CCM_LauncherProne";
        };
    };
};
